### ISSUE TITLE
Add support for adding enum constants

### ISSUE THREAD

**Issue by Earthcomputer** [SpongePowered/Mixin#387]
... To end the reflection hacks and improper ASM once and for all! :P

Rationale
---
- Sometimes adding enum constants is the only way to do something you want, at least that gives maximum compatibility to other mods.
- Even when the above is not the case, it would sometimes be the cleanest solution.
- It stops modders from doing it wrong with ASM, or at least in an incompatible way.
- It will stop people doing those god awful reflection hacks that break everything.

Myths
---
**Q: This will break switch statements**
A: Not according to [JLS 13.4.26](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.4.26):
> Adding or reordering constants in an enum will not break compatibility with pre-existing binaries.
> If a pre-existing binary attempts to access an enum constant that no longer exists, the client will fail at run time with a NoSuchFieldError. Therefore such a change is not recommended for widely distributed enums.
> In all other respects, the binary compatibility rules for enums are identical to those for classes. 

This clause in the JLS is not new, and has existed since enums were introduced.

**Q: What if compilers are non-compliant to the JLS?**
A: I tested all the following compilers, and all of them conform to the JLS:
- javac 1.8.0_242
- javac 1.6.0_45
- javac 1.5.0
- ECJ 3.20.0 (compatibility level 5)
- ECJ 3.5.0 (compatibility level 5)

The full output of each of these compilations can be found [here](https://gist.github.com/Earthcomputer/1898fe6b791a279e050527841e985588) (files annoyingly appear in reverse order for me). Note that there is an [unrelated bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544521) in ECJ related to the thread-safety of enum switch statements.

Thus, there are no compilers in common use which are non-compliant to this clause in the JLS. If a modder is using a compiler that happens to be non-compliant, then a) I would like to know what compiler that is, and b) it's a bug in that compiler, it wouldn't be Mixin's fault.

**Q: What other problems could adding enum constants cause?**
The rest of these are related to direct use of `ordinal()` by client code, especially when used to serialize an enum constant. In terms of network serialization, this would have only been a problem if the same mod wasn't installed on the client and the server; if serializing to the disk, well, it was the client code's fault for using `ordinal()` in this way anyway. If Mixin were to additionally impose the constraint that enum constants should only be added at the end of the enum, it would mitigate this problem.

Challenges
---
There are three challenges (aside from deciding on the frontend) to implementing this feature.

**values and valueOf**
`values()` is typically implemented by storing a static field called `$VALUES` (javac) or `ENUM$VALUES` (ECJ), but the name of this field can change during obfuscation. This field could still be found by looking for synthetic static fields of the type of the array of the containing enum. Now the tricky bit, changing `<clinit>` to add the enum constants to the array. You would need to find the `putstatic` instruction which sets the field you found, then either replace it with another sequence of instructions or trace the array local variable back from there. A far easier, and in my opinion better, alternative would be to simply overwrite `values()` with a new implementation incorporating the new values (which would include creating our own array field and injecting into the head of `<clinit>` to initialize it). This is a better solution because it is compiler-independent and isn't affected by obfuscation.

Both javac and ECJ implement `valueOf()` by calling [Enum.valueOf](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#valueOf(java.lang.Class,%20java.lang.String)), which would already work with the existing modifications we have made, but this is not required by the spec, so we should probably also overwrite `valueOf()` to do this just to be safe.

Another thing to note is that some enum classes may call their own `values()` method later in the `<clinit>` method, so to yield correct results, our own values array has to be fully created at the head of `<clinit>`. This would be complicated if were to use the naive approach of storing the enum constants in a static field in the mixin (which may or may not end up in the target class depending on whether it's an accessor mixin), which are initialized inline (i.e. in the `<clinit>` method in the mixin). It would be hard to distinguish this enum constant initialization, which would need to go in the head of the target `<clinit>` from other things which may be in the mixin's `<clinit>`. Furthermore, you could break the semantics of `<clinit>` by reordering these operations. So ya, better not use that approach.

**The constructor**
This is definitely the bigger problem. ECJ and javac add two synthetic parameters, `String name` and `int ordinal` (in that order), to every constructor in the enum. It is logical that these will form part of the constructors in any compilation of an enum, as they are [required by the Enum constructor](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#Enum(java.lang.String,%20int)). However I could not find this specified anywhere, which makes this the biggest assumption we would have to make; compilers could swap these parameters or put them at the end of the parameter list instead, although I can't see why any compiler would do either of these things.

Obviously, these constructors are private, but this can easily be solved with creating static shadow constructors which only work inside `<clinit>`. These shadow constructors would also not include the name or ordinal.

Another less obvious issue is that it's possible that the JVM may enforce that enum constructors can only be called in `<clinit>` in that enum. This may be mitigated by inlining a shadow constructor.

**Abstract enum classes**
That is, enums containing abstract methods. Yeah... I don't want to think about these right now. It would be easier to just not support them for now and possibly add support for them in the future.

Proposal for the API
---
With these challenges in mind, here's my proposal for how the API would look like for adding enum constants. This is only a suggestion and is up for discussion.

```java
public class SomeEnumExtensions {
   public static final String MY_NEW_CONSTANT_NAME = "MY_NEW_CONSTANT";
   public static final SomeEnum MY_NEW_CONSTANT = SomeEnum.valueOf(MY_NEW_CONSTANT_NAME);
}

@Mixin(SomeEnum.class)
public class MixinSomeEnum {
   // Creating this in a method here allows us to copy the contents of the method to the head of <clinit> rather than the tail.
   @EnumConstant(SomeEnumExtensions.MY_NEW_CONSTANT_NAME)
   private static SomeEnum createMyNewConstant() {
      return constructor("custom constructor arguments", 1.5f);
   }

   // The behaviour of @Shadow would be modified to allow for constructors if the target class is an enum, and it would ignore the name and ordinal in this case
   @Shadow
   private static SomeEnum constructor(String foo, float bar) {
      throw new UnsupportedOperationException();
   }
}
```
I couldn't think of a more idiomatic way of binding the enum constant to a field, both because of the aforementioned `<clinit>` reasons, and because such a field wouldn't be accessible outside the mixin anyway, and not easy to access with a duck interface because it would be static (and useless if there are no instances of the enum by default). However, this `valueOf` solution is clean enough, comparably to how duck interfaces were used instead of accessor mixins before they existed.

**Comment by gabizou** [comment]
Having given some thought and a [brief discussion in discord](https://discordapp.com/channels/142425412096491520/626802111455297538/687482446975205376), I'm just going to copy paste some points I've made and propositions of *how this could look* dependent on some more discussion with Mumfrey.

### Concerns

Adding a new Enum value at the byte code level is *fine* with the following highlighted understandings:
- Any precompiled `default` switch cases will 100% be reached if the new enum value is used for those methods
- AIOOB is avoided since the switch table arrays are constructed based on the `values()` array which will already be populated with any and all mixin'ed enum values
- Removing existing enum values is not at all within scope
- First come first serve enum additions are a moot point, in general it's not at all valid to rely on any `ordinal()` values of custom enum additions
- We need some way to target some specific custom enum classes that may have method overrides
- Object values used in constructors need to be statically defined and cannot have static recursive initialization loops (stack overflows at runtime)

### Proposal for how this could look

While I appreciate the usage of some familiar annotations, I don't believe for a single second that `@Shadow` is an appropriate usage since there's a few things that would need to be addressed, and I'll mention them a bit later.

First, let's start with addressing the question "How should we encourage accessing these new custom enum values?" Answer is potentially as simple as "How do we access static fields in accessor mixins?"

```java
@Mixin(ItemTier.class)
public interface ItemTierAccessor {
  @EnumCreator(name = "SUPER_DUPER_DIAMONDS_AND_STARS_TIER")
  public static ItemTier getSuperDiamondsAndStarsTier() {
    throw new UnsupportedOperationException("Untransformed mixing!");
  }
}
```

In the end, this would look relatively simple, we can easily access the enum value with `ItemTierAccessor.getSuperDiamondsAndStarsTier()` which would give us a valid `ItemTier`, as expected! And, we don't introduce any sort of class referencing rewrites, nor do we explicitly create artificial constructors, we just recycle the existing `ItemTier(String name, int ordinal)` constructor, add that to the class initializer, add a custom final field maybe `Lnet/minecraft/item/ItemTier;enumcreator$SUPER_DUPER_DIAMONDS_AND_STARS_TIER$sessionId:Lnet/minecraft/item/ItemTier;` as an example, since we don't have to worry about actually accessing the field outside the now-transformed interface static method.

### BUT WAIT! What about different constructors? What about constructors that take objects?!

So, I had a brief thought about this, and I think it's very well possible to do some fanciful constructor writing here. Just like how we have `@Constant` to detect what constant value is actually filled in, we can somewhat recycle `@Constant` in this case where we have the following:
```java
@Mixin(ItemTier.class)
public interface ItemTierAccessor {
  @EnumCreator(name = "SUPER_DUPER_DIAMONDS_AND_STARS_TIER",
    args = {
      @Constant(intValue = 4), 
      @Constant(intValue = 2048), 
      @Constant(floatValue=3.5F), 
      @Constant(objectValue = "Lcom/example/mymod/CustomEnumValues;MY_CONSTANT_INGREDIENT_SUPPLIER:Ljava/util/function/Supplier;")
    }
  )  
  public static ItemTier getSuperDiamondsAndStarsTier() {
    throw new UnsupportedOperationException("Untransformed mixing!");
  }
}
```
And with this, we have Mixin being able to verify that the field value `MY_CONSTANT_INGREDIENT_SUPPLIER` is actually static, but we could also further enhance the access by saying it's a method instead! Because ultimately, as long as the access is static, we're fine realistically. And what this gives us is something very close to matching the required arguments to match against a specific constructor (with the added name obviously).

### But what if I want to use a particular enum type as a base? Like if one enum already exists where it overrides a method?
Well, for this I'd go as far as suggesting we might be able to do an `extensionTarget = ItemTier.DIAMOND` on the `@EnumCreator` variation, and if we needed to explicitly override/soft-implement a method for our custom type, then we'd have issues and that I don't have a solution for.

**Comment by Vaerian** [comment]
Bump

**Comment by LudoCrypt** [comment]
In one of my Minecraft mods i have something like this which adds onto mixins
```java
@Mixin(NoteBlockInstrument.class)
@Unique
public abstract class NoteblockInstrumentMixin {

	@Shadow
	@Final
	@Mutable
	private static NoteBlockInstrument[] $VALUES;

	private static final NoteBlockInstrument MUSIC_BOX = noteblockExpansion$addVariant("MUSIC_BOX", "music_box", NoteblockSounds.MUSIC_BOX);

	@Invoker("<init>")
	public static NoteBlockInstrument noteblockExpansion$invokeInit(String internalName, int internalId, String name, SoundEvent sound) {
		throw new AssertionError();
	}

	private static NoteBlockInstrument noteblockExpansion$addVariant(String internalName, String name, SoundEvent sound) {
		ArrayList<NoteBlockInstrument> variants = new ArrayList<NoteBlockInstrument>(Arrays.asList(NoteblockInstrumentMixin.$VALUES));
		NoteBlockInstrument instrument = noteblockExpansion$invokeInit(internalName, variants.get(variants.size() - 1).ordinal() + 1, name, sound);
		variants.add(instrument);
		NoteblockInstrumentMixin.$VALUES = variants.toArray(new NoteBlockInstrument[0]);
		return instrument;
	}
}
```

and this seems to work exactly fine!

**Comment by Taskeren** [comment]
> In one of my Minecraft mods i have something like this which adds onto mixins
> 
> ```java
> @Mixin(NoteBlockInstrument.class)
> @Unique
> public abstract class NoteblockInstrumentMixin {
> 
> 	@Shadow
> 	@Final
> 	@Mutable
> 	private static NoteBlockInstrument[] $VALUES;
> 
> 	private static final NoteBlockInstrument MUSIC_BOX = noteblockExpansion$addVariant("MUSIC_BOX", "music_box", NoteblockSounds.MUSIC_BOX);
> 
> 	@Invoker("<init>")
> 	public static NoteBlockInstrument noteblockExpansion$invokeInit(String internalName, int internalId, String name, SoundEvent sound) {
> 		throw new AssertionError();
> 	}
> 
> 	private static NoteBlockInstrument noteblockExpansion$addVariant(String internalName, String name, SoundEvent sound) {
> 		ArrayList<NoteBlockInstrument> variants = new ArrayList<NoteBlockInstrument>(Arrays.asList(NoteblockInstrumentMixin.$VALUES));
> 		NoteBlockInstrument instrument = noteblockExpansion$invokeInit(internalName, variants.get(variants.size() - 1).ordinal() + 1, name, sound);
> 		variants.add(instrument);
> 		NoteblockInstrumentMixin.$VALUES = variants.toArray(new NoteBlockInstrument[0]);
> 		return instrument;
> 	}
> }
> ```
> 
> https://github.com/LudoCrypt/Noteblock-Expansion-Forge/blob/main/src/main/java/net/ludocrypt/nbexpand/mixin/NoteblockInstrumentMixin.java and this seems to work exactly fine!

I have few questions.

How can I get the instance of the new created enum?
I'm now using `Enum.valueOf(String)` to get it, but is it possible to get the instance from the Mixin class?

And I'm wonder why there are 2 of the same new created instance in the `Enum.values()`?
![image](https://github.com/user-attachments/assets/eba6a381-edb2-47d8-a726-ae9c88292d00)

My Mixin is, with UniMixins in Minecraft 1.7.10 environment:

```java
package cn.taskeren.op.mixin.late;

import appeng.api.config.Upgrades;
import org.spongepowered.asm.mixin.*;
import org.spongepowered.asm.mixin.gen.Invoker;

import java.util.ArrayList;
import java.util.Arrays;

@Mixin(value = Upgrades.class, remap = false)
@Unique
public abstract class AdditionalAE_Upgrades_Mixin {

    @Shadow
    @Final
    @Mutable
    private static Upgrades[] $VALUES;

    private static final Upgrades PROGRAMMED = op$createInstance("PROGRAMMED", 1);

    @Invoker("<init>")
    public static Upgrades op$constructor(String name, int ordinal, int tier) {
        throw new AssertionError();
    }

    private static Upgrades op$createInstance(String name, int tier) {
        // get existing instances
        ArrayList<Upgrades> values = new ArrayList<>(Arrays.asList($VALUES));
        // create the new instance
        Upgrades value = op$constructor(name, values.get(values.size() - 1).ordinal() + 1, tier);
        // add the new instance to the instance cache list
        values.add(value);
        // overwrite the $VALUES to the value list with the new instance
        $VALUES = values.toArray(new Upgrades[0]);
        // return the new instance
        return value;
    }

}
```

The mixined class: <https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/api/config/Upgrades.java>

**Comment by Fox2Code** [comment]
This would be cool.

> Q: This will break switch statements
> A: Not according to [JLS 13.4.26](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.4.26):
> 
>     Adding or reordering constants in an enum will not break compatibility with pre-existing binaries.
>     If a pre-existing binary attempts to access an enum constant that no longer exists, the client will fail at run time with a NoSuchFieldError. Therefore such a change is not recommended for widely distributed enums.
>     In all other respects, the binary compatibility rules for enums are identical to those for classes.

While very old java use `ordinal()` for switches, it should not break thoses switches as we are only adding enums and not changing the ordinal of existing ones.

> Any precompiled default switch cases will 100% be reached if the new enum value is used for those methods.

The alternatives this proposal is trying to replace has the same issues, I still think it is a net improvement.

**Comment by Earthcomputer** [comment]
> While very old java use `ordinal()` for switches, it should not break thoses switches as we are only adding enums and not changing the ordinal of existing ones.

Can you provide a source for this statement? As far as I know this is a myth, and is addressed next in the list of myths.

**Comment by LexManos** [comment]
The only places where I have seen ordinal() directly used in java switch statements is NEWER java. When the enum in question is a private inner enum.

```java
public class Test {
  public static void main(String[] args) {
    TestEnum value = TestEnum.A;
    switch (value) {
       case A: System.out.println("A"); break;
       case B: System.out.println("B"); break;
       case C: System.out.println("C"); break;
       case D: System.out.println("D"); break;
    }
  }
  private enum TestEnum { A, B, C, D; }
}
```

Java 5-17:
```
         2: getstatic     #2                  // Field Test$1.$SwitchMap$Test$TestEnum:[I
         5: aload_1
         6: invokevirtual #3                  // Method Test$TestEnum.ordinal:()I
         9: iaload
        10: tableswitch   { // 1 to 4
                       1: 40
                       2: 51
                       3: 62
                       4: 73
                 default: 81
            }
```
            
java 21:
```
         2: aload_1
         3: invokevirtual #7                  // Method Test$TestEnum.ordinal:()I
         6: tableswitch   { // 0 to 3
                       0: 36
                       1: 47
                       2: 58
                       3: 69
                 default: 77
            }
```

**Comment by Fox2Code** [comment]
> Can you provide a source for this statement? As far as I know this is a myth, and is addressed next in the list of myths.

Me, I used to decompile bytecode often a few years ago, and I remember very old java using `ordinal()` directly.

I remember is that sourceCompatibility/targetCompatibility doesn't affect how a switch statement is compiled.

Well, this was from a long time ago, I just did test a bunch of JVM and try to decompile a bunch of old stuff before replying to make sure I'm not saying wrong thing, and noticed all of the byte-code I found use the regular enum cache system.

I think I did miss-remembered this stuff, because it was from many many years ago.

Sorry for having a faulty memory, I am still unsure where my memory of me de-compiling very old java bytecode that don't use switch enum statement cache is coming from exactly.

At least now I have a new memory correcting that inaccuracy!

**Comment by Fox2Code** [comment]
Well my memory date to before java 17 was even released, it still doesn't explain why I remember something that is not there.

**Comment by Earthcomputer** [comment]
> The only places where I have seen ordinal() directly used in java switch statements is NEWER java. When the enum in question is a private inner enum.

Oh, that's interesting. I guess it doesn't matter when the enum is private for binary compatibility. It wouldn't allow us to reorder enum entries, but we're not trying to do that anyway. What's important is that our added enum entries always hit the default block, which they should with that new bytecode. All switch statements and expressions when compiled have a default block, and switch expressions on enums without a default block will generate a default block which throws.

**Comment by LexManos** [comment]
> All switch statements and expressions when compiled have a default block, 

From what I have seen this is correct
> switch expressions on enums without a default block will generate a default block which throws.

Naw, It will just bypass the entire switch instead of throw, but the point still stands that it is fine and will just hit the default case.
Tested Java 5 -> 21
```
         8: tableswitch   { // 0 to 3
                       0: 40
                       1: 51
                       2: 62
                       3: 73
                 default: 81
            }
        40: getstatic     #17                 // Field java/lang/System.out:Ljava/io/PrintStream;
        43: ldc           #23                 // String A
        45: invokevirtual #24                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        48: goto          81
        51: getstatic     #17                 // Field java/lang/System.out:Ljava/io/PrintStream;
        54: ldc           #30                 // String B
        56: invokevirtual #24                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        59: goto          81
        62: getstatic     #17                 // Field java/lang/System.out:Ljava/io/PrintStream;
        65: ldc           #32                 // String C
        67: invokevirtual #24                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        70: goto          81
        73: getstatic     #17                 // Field java/lang/System.out:Ljava/io/PrintStream;
        76: ldc           #34                 // String D
        78: invokevirtual #24                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        81: return
```

**Comment by Earthcomputer** [comment]
> Naw, It will just bypass the entire switch instead of throw

More specifically switch expressions which return a value will throw

**Comment by LexManos** [comment]
> More specifically switch expressions which return a value will throw

Ah, this is true.
```java
    int ret = switch (value) {
        case A -> 1;
        case B -> 2;
        case C -> 3;
        case D -> 4;
    };
```

```
        81: aload_1
        82: invokevirtual #13                 // Method Test$TestEnum.ordinal:()I
        85: tableswitch   { // 0 to 3
                       0: 126
                       1: 130
                       2: 134
                       3: 138
                 default: 116
            }
       116: new           #36                 // class java/lang/MatchException
       119: dup
       120: aconst_null
       121: aconst_null
       122: invokespecial #38                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
       125: athrow
       126: iconst_1
       127: goto          139
       130: iconst_2
       131: goto          139
       134: iconst_3
       135: goto          139
       138: iconst_4
       139: istore_2
```
